version: 2

jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run: apk update
      - run: |
          apk add \
            fish \
            ghc \
            neovim \
            gdb
      - run: |
          set -e

          mv .config ~
          mv .ghc ~
          mv .gdbinit ~
          mv bin ~

          echo :q | gdb &> /dev/null
          echo :q | ghci &> /dev/null
          echo exit | fish &> /dev/null
